services:
  app:
    build: .
    restart: always
    ports:
      - 5001:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./data:/var/lib/postgresql/data
